version: 2.1
jobs:
  build:
    docker:
      - image: ocpu/chrome-node # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: npm test
